"""add payment_date to invoices

Revision ID: 03af8392206d
Revises: 9414204e045c
Create Date: 2026-04-03 00:15:40.443866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03af8392206d'
down_revision: Union[str, None] = '9414204e045c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_date')
    # ### end Alembic commands ###
