"""add_productivity_tables

Revision ID: 2fc6fb7805e4
Revises: 03af8392206d
Create Date: 2026-04-08 01:14:11.828233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc6fb7805e4'
down_revision: Union[str, None] = '03af8392206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productivity_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('pat_encrypted', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'provider', 'username', 'workspace', name='uq_connection_user_provider_workspace')
    )
    op.create_index('ix_prod_connections_contract', 'productivity_connections', ['contract_id'], unique=False)
    op.create_index('ix_prod_connections_user', 'productivity_connections', ['created_by_user_id'], unique=False)
    op.create_table('productivity_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(length=40), nullable=False),
    sa.Column('short_hash', sa.String(length=7), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['productivity_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'hash', 'repository', name='uq_commit_connection_hash_repo')
    )
    op.create_index('ix_prod_commits_connection', 'productivity_commits', ['connection_id'], unique=False)
    op.create_index('ix_prod_commits_date', 'productivity_commits', ['connection_id', 'date'], unique=False)
    op.create_table('productivity_pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at_remote', sa.DateTime(), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['productivity_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'number', 'repository', name='uq_pr_connection_number_repo')
    )
    op.create_index('ix_prod_prs_connection', 'productivity_pull_requests', ['connection_id'], unique=False)
    op.create_index('ix_prod_prs_date', 'productivity_pull_requests', ['connection_id', 'created_at_remote'], unique=False)
    op.drop_constraint('user_preferences_user_id_key', 'user_preferences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_preferences_user_id_key', 'user_preferences', ['user_id'])
    op.drop_index('ix_prod_prs_date', table_name='productivity_pull_requests')
    op.drop_index('ix_prod_prs_connection', table_name='productivity_pull_requests')
    op.drop_table('productivity_pull_requests')
    op.drop_index('ix_prod_commits_date', table_name='productivity_commits')
    op.drop_index('ix_prod_commits_connection', table_name='productivity_commits')
    op.drop_table('productivity_commits')
    op.drop_index('ix_prod_connections_user', table_name='productivity_connections')
    op.drop_index('ix_prod_connections_contract', table_name='productivity_connections')
    op.drop_table('productivity_connections')
    # ### end Alembic commands ###
