"""add contracts and recurring tasks, remove invoice recurrence fields

Revision ID: 769ff56e0eb4
Revises: c2d3e4f5a6b7
Create Date: 2026-04-02 22:31:37.734654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '769ff56e0eb4'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_tasks_enabled', 'recurring_tasks', ['enabled'], unique=False)
    op.create_index('ix_recurring_tasks_task_type', 'recurring_tasks', ['task_type'], unique=False)
    op.create_index('ix_recurring_tasks_user_id', 'recurring_tasks', ['user_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('annual_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_day', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'name', name='uq_contract_user_name')
    )
    op.create_index('ix_contracts_created_by_user_id', 'contracts', ['created_by_user_id'], unique=False)
    op.create_index('ix_contracts_customer_id', 'contracts', ['created_by_user_id', 'customer_id'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurring_task_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_reference_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_task_id'], ['recurring_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_task_id', 'scheduled_for', name='uq_task_execution_schedule')
    )
    op.create_index('ix_task_executions_recurring_task_id', 'task_executions', ['recurring_task_id'], unique=False)
    op.create_index('ix_task_executions_scheduled_for', 'task_executions', ['scheduled_for'], unique=False)
    op.create_index('ix_task_executions_status', 'task_executions', ['status'], unique=False)
    op.create_table('contract_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('service_title', sa.String(), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_services_contract_id', 'contract_services', ['contract_id'], unique=False)
    op.create_index('ix_contract_services_created_by_user_id', 'contract_services', ['created_by_user_id'], unique=False)
    op.add_column('invoices', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    op.drop_column('invoices', 'recurrence_day')
    op.drop_column('invoices', 'recurrence_frequency')
    op.drop_column('invoices', 'is_recurrent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_recurrent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('recurrence_frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('recurrence_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'contract_id')
    op.drop_index('ix_contract_services_created_by_user_id', table_name='contract_services')
    op.drop_index('ix_contract_services_contract_id', table_name='contract_services')
    op.drop_table('contract_services')
    op.drop_index('ix_task_executions_status', table_name='task_executions')
    op.drop_index('ix_task_executions_scheduled_for', table_name='task_executions')
    op.drop_index('ix_task_executions_recurring_task_id', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index('ix_contracts_customer_id', table_name='contracts')
    op.drop_index('ix_contracts_created_by_user_id', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_recurring_tasks_user_id', table_name='recurring_tasks')
    op.drop_index('ix_recurring_tasks_task_type', table_name='recurring_tasks')
    op.drop_index('ix_recurring_tasks_enabled', table_name='recurring_tasks')
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
