"""make contract_services amount nullable

Revision ID: 9414204e045c
Revises: fab3f2022399
Create Date: 2026-04-02 23:24:06.279503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9414204e045c'
down_revision: Union[str, None] = 'fab3f2022399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_services', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract_services', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    # ### end Alembic commands ###
