"""add_finance_module

Revision ID: aa9ec6fdc43d
Revises: b3c4d5e6f7a8
Create Date: 2026-02-14 01:20:02.058821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9ec6fdc43d'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'name', name='uq_transaction_category_user_name')
    )
    op.create_index('ix_transaction_categories_created_by_user_id', 'transaction_categories', ['created_by_user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('bank_account_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_bank_account', 'transactions', ['bank_account_id'], unique=False)
    op.create_index('ix_transactions_category', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_created_by_user_id', 'transactions', ['created_by_user_id'], unique=False)
    op.create_index('ix_transactions_user_context', 'transactions', ['created_by_user_id', 'context'], unique=False)
    op.create_index('ix_transactions_user_date', 'transactions', ['created_by_user_id', 'date'], unique=False)
    op.create_index('ix_transactions_user_type', 'transactions', ['created_by_user_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_type', table_name='transactions')
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index('ix_transactions_user_context', table_name='transactions')
    op.drop_index('ix_transactions_created_by_user_id', table_name='transactions')
    op.drop_index('ix_transactions_category', table_name='transactions')
    op.drop_index('ix_transactions_bank_account', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_transaction_categories_created_by_user_id', table_name='transaction_categories')
    op.drop_table('transaction_categories')
    # ### end Alembic commands ###
