"""add_selected_repos_to_connections

Revision ID: d789f2000805
Revises: 2fc6fb7805e4
Create Date: 2026-04-08 04:08:43.063343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd789f2000805'
down_revision: Union[str, None] = '2fc6fb7805e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productivity_connections', sa.Column('selected_repos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productivity_connections', 'selected_repos')
    # ### end Alembic commands ###
