"""add contract_pdf_url to contracts

Revision ID: da8ca330aece
Revises: 769ff56e0eb4
Create Date: 2026-04-02 23:00:44.509308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8ca330aece'
down_revision: Union[str, None] = '769ff56e0eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'contract_pdf_url')
    # ### end Alembic commands ###
